---
openapi: 3.0.1
info:
  title: Kafka Messages API
  description: API for managing Kafka messages
  version: 1.0.0
paths: {}
components:
  schemas:
    genericKafkaMessage:
      type: object
      properties:
        topicName:
          type: string
        message:
          type: object
        headers:
          type: object
          additionalProperties: true
        payload:
          type: object
        messageType:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        objectMsgId:
          type: integer
          format: int64
      discriminator:
        propertyName: globalDlq
        mapping:
          globalDlq: "#/components/schemas/globalDlqMessage"
          ipeAudit: "#/components/schemas/ipeAudit"
          task: "#/components/schemas/task"
    globalDlqMessage:
      allOf:
        - $ref: '#/components/schemas/genericKafkaMessage'
      type: object
      properties:
        errorMsg:
          type: string
    ipeAudit:
      allOf:
        - $ref: '#/components/schemas/genericKafkaMessage'
        - $ref: './ipeAudit.yaml'
    task:
      allOf:
        - $ref: '#/components/schemas/genericKafkaMessage'
