---
openapi: 3.0.1
components:
  schemas:
    genericKafkaMessage:
      type: object
      properties:
        topicName:
          type: string
        message:
          type: object
        headers:
          type: object
        payload:
          type: object
        status:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        objectMsgId:
          type: integer
          format: int64
