---
openapi: 3.0.1
components:
  schemas:
    globalDlq:
      type: object
      x-implements:
        - ../genericKafka.yaml
      properties:
        message:
          type: object
        headers:
          type: object
        payload:
          type: object
        status:
          type: string
        createdAt:
          type: string
          format: date-time
          readOnly: true
        errorMsg:
          type: string
        objectMsgId:
          type: integer
          format: int64
      required:
        - message
        - headers
        - payload
        - status
        - createdAt
        - errorMsg
        - objectMsgId

info:
  title: DLQ API
  version: 1.0.0
  description: DLQ API

