---
openapi: 3.0.1
x-stoplight:
  id: 123456789
info:
  title: Connector service
  description: This API provides all operations with messages
  version: 1.0.0
  contact:
    name: Eduardo
servers:
  - url: 'https://localhost:11455'
    description: Generated server url
tags:
  - name: genericDlq
    description: messages related with generic dlq
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
paths:
  '/v1/task':
    post:
      tags:
        - genericDlq
      operationId: createTaskMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: './models/kafka-messages/task.yaml'
        required: true
      responses:
        '200':
          description: OK
  '/v1/audits':
    post:
      tags:
        - audits
      operationId: createAuditMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: './models/kafka-messages/ipeAudit.yaml'
        required: true
      responses:
        '200':
          description: OK
  '/v1/generic-dlq':
    post:
      tags:
        - genericDlq
      operationId: createGenericDlqEventMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: './models/kafka-messages/global-dlq.yaml'
        required: true
      responses:
        '200':
          description: OK
